### ISSUE TITLE
[Tracker] Fix CSI sanity failures to conform to CSI Spec v1.2

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#494]
# CSI Sanity

- Below are some good first issues for new contributors to get to know about KaDalu CSI Driver and CSI Spec

## Easy (good first issues):
- [x] Node Service NodePublishVolume [It] should fail when no volume id is provided
- [x] Node Service NodePublishVolume [It] should fail when no target path is provided
- [x] Node Service NodePublishVolume [It] should fail when no volume capability is provided
- [x] Node Service NodeUnpublishVolume [It] should fail when no volume id is provided
- [x] Controller Service [Controller Server] DeleteVolume [It] should fail when no volume id is provided
- [x] Controller Service [Controller Server] ValidateVolumeCapabilities [It] should fail when no volume id is provided
- [x] ExpandVolume [Controller Server] [It] should fail if no volume id is given
- [x] Controller Service [Controller Server] CreateVolume [It] should fail when no name is provided
- [x] Controller Service [Controller Server] CreateVolume [It] should fail when no volume capabilities are provided

## Easy to Medium (good first issues):
- [x] Controller Service [Controller Server] ValidateVolumeCapabilities [It] should fail when no volume capabilities are provided
- [x] Controller Service [Controller Server] ValidateVolumeCapabilities [It] should fail when the requested volume does not exist
- [x] Node Service NodeUnpublishVolume [It] should fail when no target path is provided

## Medium:
- [x] Controller Service [Controller Server] ListVolumes [It] should return appropriate values (no optional values added)
- [x] Controller Service [Controller Server] ListVolumes [It] should fail when an invalid starting_token is passed
- [x] Controller Service [Controller Server] ListVolumes [It] check the presence of new volumes and absence of deleted ones in the volume list
- [x] Controller Service [Controller Server] CreateVolume [It] should fail when requesting to create a volume with already existing name and different capacity.
- [x] Controller Service [Controller Server] ValidateVolumeCapabilities [It] should return appropriate values (no optional values added)
- [x] ExpandVolume [Controller Server] [It] should fail if no capacity range is given
- [x] ExpandVolume [Controller Server] [It] should work

#### For fixing above failure, the flow should be:
- Find failing service: `Node Service`
- Find failing RPC method: `NodePubhlishVolume`
- Actual test failure: `should fail when no volume id is provided`
- Refer CI logs corresponding to the test:
```
[2021-03-17 10:17:33,748] DEBUG [nodeserver - 41:NodePublishVolume] - Received the mount request	 volume=fake-vol-id-3775be74-7 voltype= hostvol= pvpath= pvtype=
[2021-03-17 10:17:33,763] ERROR [_server - 445:_call_behavior] - Exception calling application: [Errno 2] No such file or directory: '/var/lib/gluster/.info'
Traceback (most recent call last):
  File "/kadalu/lib/python3.8/site-packages/grpc/_server.py", line 435, in _call_behavior
    response_or_iterator = behavior(argument, context)
  File "/kadalu/nodeserver.py", line 72, in NodePublishVolume
    mount_glusterfs(volume, mntdir, True)
  File "/kadalu/volumeutils.py", line 841, in mount_glusterfs
    generate_client_volfile(volume['name'])
  File "/kadalu/volumeutils.py", line 773, in generate_client_volfile
    with open(info_file_path) as info_file:
FileNotFoundError: [Errno 2] No such file or directory: '/var/lib/gluster/.info'
```
- Refer [CSI Spec](https://github.com/container-storage-interface/spec/blob/release-1.2/spec.md) for correct error response
- Most of the failures correspond to returing appropriate errors as per spec
- Once the root cause is found, fix the code to conform to Spec
- All RPC services can be found in [csi](https://github.com/kadalu/kadalu/tree/devel/csi) folder
- Raise a PR referring(Updates) the current issue

**Comment by vatsa287** [comment]
"Expand Volume: Should work" Is this error related to some unavailable permissions permissions in csi-sanity?
```bash
rpc error: code = Unknown desc = Exception calling application: [Errno 1] Operation not permitted: '/mnt/storage-pool-1/subvol/75/93/sanity-expand-volume-8B8202DC-AC1004FE'
  occurred
  ```
I'm guessing this error is from here
```
hostvol = existing_volume.hostvol
mntdir = os.path.join(HOSTVOL_MOUNTDIR, hostvol)
```

**Comment by leelavg** [comment]
@vatsa287 good catch and at the same time I think your guess maybe incorrect.

1. Failure is in setting [trusted.gfs.squota.limit](https://github.com/kadalu/kadalu/blob/20eb11fb316a7137f93700b648b104799827dc98/csi/volumeutils.py#L473)
2. We missed catching the exception and so only `re-raise` of exception is captured in the log
3. @amarts I think we need to investigate why this specific setxattr is failing in this context

**Comment by amarts** [comment]
> @vatsa287 good catch and at the same time I think your guess maybe incorrect.
> 
> 1. Failure is in setting [trusted.gfs.squota.limit](https://github.com/kadalu/kadalu/blob/20eb11fb316a7137f93700b648b104799827dc98/csi/volumeutils.py#L473)
> 2. We missed catching the exception and so only `re-raise` of exception is captured in the log
> 3. @amarts I think we need to investigate why this specific setxattr is failing in this context

Good finding, and it was indeed the case. With https://github.com/kadalu/glusterfs/commit/7f4259ed48d5d9812d9cb0466f72956d99c218d1 things seem to work well now! Will trigger a run just for validation purposes!
