### ISSUE TITLE
[Tracker] Issues related to external volumes usage

### ISSUE THREAD

**Issue by leelavg** [kadalu/kadalu#562]
Hi,

I think below issues are ~good to have fix and so creating this issue to track them.

- [x] Delete external storage classes gracefully
- [x] Make use of `gluster_options` while actually mounting gluster volume
- [ ] Minimal testing wrt external cluster, can gluster be dockerized and used in CI to iron out issues similar to #468 and #540?
- [ ] Revisit kadalu-quotad for any incomplete implementation wrt current code ([native gluster rfc](https://kadalu.io/rfcs/0007-Using-GlusterFS-directory-quota-for-external-gluster-volumes.html))
- [x] Revisit xattr's code that is being set on external vols (#526)
- [ ] In general, prioritise or at-least take note of any incompatibilities that may be introduced after adding features to kadalu storage

I'll add logs to all of these if possible at the earliest.
