### ISSUE TITLE
[Tracking] 1.0 release

### ISSUE THREAD

**Issue by aravindavk** [kadalu/kadalu#923]
This is a tracking issue for 1.0

- [x] Support for Replica2 without Tiebreaker (https://github.com/kadalu/kadalu/pull/922)
- [ ] Document Replica2 and Tiebreaker as Beta features
- [x] One more release before 1.0 (0.9.x)
- [ ] Documentation update as Pool wherever Hosting Volume is mentioned
- [ ] Branch based release workflow (Current one is tag based)

**Comment by aravindavk** [comment]
@amarts @leelavg @vatsa287 add if any other issues to be fixed before 1.0

**Comment by amarts** [comment]
If its possible to fix, any issues on OpenShift which are reported? (like the metrics issues mentioned by #897)

**Comment by aravindavk** [comment]
> Branch based release workflow (Current one is tag based)

Realized that no change is required to make it branch based since tags are global level. No same tag can be created for two branches. So to release 1.0.0: Create a branch `1.0` and then tag `1.0.0`, `1.0.1` etc.
